'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EmploymentApplication

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''RadCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlApplication As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblerrStr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerrStr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgapplicationLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgapplicationLogo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtMiddleNameInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMiddleNameInitial As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtReferredby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReferredby As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStreetAddress As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZip As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCity As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtState As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''emailValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtPrimaryPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrimaryPhone As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''txtAltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAltPhone As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cbPreferredLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPreferredLocation As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtDesiredPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesiredPosition As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDesiredSalary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesiredSalary As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''cbDesiredSalaryPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDesiredSalaryPeriod As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''dpDesiredStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpDesiredStartDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rbCurrentlyEmployedYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCurrentlyEmployedYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbCurrentlyEmployedNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCurrentlyEmployedNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbAskCurrentEmployerYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbAskCurrentEmployerYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbAskCurrentEmployerNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbAskCurrentEmployerNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbAppliedBeforeYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbAppliedBeforeYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbAppliedBeforeNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbAppliedBeforeNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtAppliedBeforeLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAppliedBeforeLocation As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cbAppliedBeforeMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAppliedBeforeMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbAppliedBeforeYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAppliedBeforeYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbEducationLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEducationLevel As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtSchool1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSchool1Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool1Location As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSchool1YearsAttended control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool1YearsAttended As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''cbSchool1Graduated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSchool1Graduated As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtSchool1SubjectsStudied control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool1SubjectsStudied As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSchool2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSchool2Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool2Location As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSchool2YearsAttended control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool2YearsAttended As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''cbSchool2Graduated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSchool2Graduated As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtSchool2SubjectsStudied control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool2SubjectsStudied As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSchool3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSchool3Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool3Location As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSchool3YearsAttended control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool3YearsAttended As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''cbSchool3Graduated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSchool3Graduated As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtSchool3SubjectsStudied control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchool3SubjectsStudied As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSpecialSkills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecialSkills As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cbMilitaryBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMilitaryBranch As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbMilitaryServiceFromDateMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMilitaryServiceFromDateMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbMilitaryServiceFromDateYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMilitaryServiceFromDateYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbMilitaryServiceToDateMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMilitaryServiceToDateMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbMilitaryServiceToDateYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMilitaryServiceToDateYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbMilitaryRank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMilitaryRank As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE1ToMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE1ToMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE1ToYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE1ToYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE1FromMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE1FromMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE1FromYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE1FromYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtPE1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE1Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE1Location As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE1phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE1phone As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''txtPE1salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE1salary As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE1position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE1position As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE1reasonForLeaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE1reasonForLeaving As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cbPE2ToMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE2ToMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE2ToYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE2ToYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE2FromMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE2FromMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE2FromYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE2FromYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtPE2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE2Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE2Location As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE2phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE2phone As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''txtPE2salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE2salary As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE2position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE2position As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE2reasonForLeaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE2reasonForLeaving As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cbPE3ToMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE3ToMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE3ToYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE3ToYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE3FromMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE3FromMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE3FromYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE3FromYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtPE3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE3Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE3Location As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE3phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE3phone As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''txtPE3salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE3salary As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE3position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE3position As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE3reasonForLeaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE3reasonForLeaving As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cbPE4ToMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE4ToMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE4ToYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE4ToYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE4FromMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE4FromMonth As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbPE4FromYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPE4FromYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtPE4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE4 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE4Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE4Location As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE4phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE4phone As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''txtPE4salary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE4salary As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE4position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE4position As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPE4reasonForLeaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPE4reasonForLeaving As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtReference1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReference1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txxtReference1YrsKnown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txxtReference1YrsKnown As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtReference1Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReference1Contact As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtReference2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReference2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtReference2YrsKnown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReference2YrsKnown As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtReference2Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReference2Contact As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtReference3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReference3 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtReference3YrsKnown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReference3YrsKnown As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtReference3Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReference3Contact As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lblAckTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAckTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlAck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAck As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblApplicantIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplicantIP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHelpABrother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHelpABrother As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadToolTip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTip1 As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock
End Class
