'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ScheduledLoadImporterSetup

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblhelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbLocations As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cbImportName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbImportName As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''btnRemoveConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveConfig As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNEWConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNEWConfig As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divsetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divsetup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblImportName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImportName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtImportName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImportName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rb1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rb2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rb2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rb3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rb3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''numFirstRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numFirstRow As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rblistHasDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblistHasDate As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''chkLogDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLogDate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtLogDateColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLogDateColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtStatusColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtStatusDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkLoadNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLoadNumber As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtLoadNumberColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoadNumberColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtLoadNumberDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoadNumberDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDepartment As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDepartmentIDColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartmentIDColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cbDepartmentIDDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDepartmentIDDefault As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''chkLoadType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLoadType As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtLoadTypeIDColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoadTypeIDColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cbLoadTypeIDDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbLoadTypeIDDefault As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''chkVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVendor As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtVendorColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVendorColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtVendorDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVendorDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkVendorNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVendorNumber As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtVendorNumberColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVendorNumberColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtVendorNumberDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVendorNumberDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkPurchaseOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPurchaseOrder As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtPurchaseOrderColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPurchaseOrderColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPurchaseOrderDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPurchaseOrderDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAmount As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAmountColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtAmountDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkCheckNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCheckNumber As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtCheckNumberColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCheckNumberColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCheckNumberDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCheckNumberDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkSplitPaymentAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSplitPaymentAmount As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtSplitPaymentAmountColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSplitPaymentAmountColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtSplitPaymentAmountDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSplitPaymentAmountDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkReceiptNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReceiptNumber As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtReceiptNumberColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiptNumberColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtReceiptNumberDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiptNumberDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkLoadDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLoadDescription As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtLoadDescriptionIDColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoadDescriptionIDColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cbLoadDescriptionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbLoadDescriptionID As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''chkCarrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCarrier As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtCarrierIDColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCarrierIDColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cbCarrierOD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCarrierOD As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''chkTruckNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTruckNumber As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtTruckNumberColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTruckNumberColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtTruckNumberDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTruckNumberDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkTrailerNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTrailerNumber As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtTrailerNumberColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTrailerNumberColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtTrailerNumberDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTrailerNumberDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkAppointmentTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAppointmentTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAppointmentTimeColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAppointmentTimeColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtAppointmentTimeDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAppointmentTimeDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkGateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGateTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtGateTimeColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGateTimeColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtGateTimeDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGateTimeDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkDockTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDockTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDockTimeColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDockTimeColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDockTimeDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDockTimeDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkStartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStartTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtStartTimeColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartTimeColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtStartTimeDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartTimeDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkCompTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCompTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtCompTimeColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompTimeColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCompTimeDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompTimeDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkPalletsUnloaded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPalletsUnloaded As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtPalletsUnloadedColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPalletsUnloadedColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPalletsUnloadedDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPalletsUnloadedDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkDoorNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDoorNumber As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDoorNumberColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDoorNumberColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtDoorNumberDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDoorNumberDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkPieces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPieces As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtPiecesColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPiecesColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPiecesDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPiecesDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWeight As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtWeightColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeightColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtWeightDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeightDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkRestacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRestacks As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtRestacksColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRestacksColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtRestacksDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRestacksDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkPalletsReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPalletsReceived As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtPalletsReceivedColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPalletsReceivedColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtPalletsReceivedDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPalletsReceivedDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkBadPallets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBadPallets As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtBadPalletsColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBadPalletsColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBadPalletsDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBadPalletsDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkNumberOfItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNumberOfItems As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtNumberOfItemsColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumberOfItemsColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtNumberOfItemsDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumberOfItemsDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkBOL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBOL As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtBOLColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBOLColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtBOLDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBOLDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''chkComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkComments As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtCommentsColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentsColumn As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtCommentsDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentsDefault As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadToolTip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTip1 As Global.Telerik.Web.UI.RadToolTip
End Class
